apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "k8s-disks/gateway"
