apiVersion: v1
kind: Service
metadata:
  name: csd-gateway
  labels:
    app: csd-gateway
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: csd-gateway