apiVersion: v1
kind: Service
metadata:
  name: csd-gateway-db
  labels:
    app: csd-gateway-db
spec:
  type: ClusterIP
  ports:
  - port: 27017
    protocol: TCP
  selector:
    appdb: csd-gateway-db