apiVersion: v1
kind: PersistentVolume
metadata:
  name: rwo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "/~/RWO"

