apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: csd-crud-db
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        appdb: csd-crudb
    spec: 
      containers:
      - name: csd-crud-db
        image: postgre:11-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        - name: POSTGRES_USER
          value: postgres
        ports:
        - containerPort: 5432
