apiVersion: apps/v1
kind: Deployment
metadata:
  name: csd-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csd-crud
  template:
    metadata:
      labels:
        app: csd-crud
    spec:
      containers:
      - name: csd-crud
        image: ahlp/csd-crud:latest
        env:
        # - name: POSTGRES_HOST
        #   value: csd-crudb
        # - name: LOG_HOST
        #   value: csd-log
        ports:
        - containerPort: 3000
    