apiVersion: v1
kind: PersistentVolume
metadata:
  name: crud-db
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "k8s-disks/crud-db"
